FROM node:16.20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund && \
    npm cache clean --force

COPY . .
RUN npm run build -- --prod

FROM nginx:1.27-alpine

COPY --from=build /app/dist/frontend/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
