name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: ${{ secrets.NAMESPACE }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Backend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: timnekk/sausage-backend:latest
          build-args: |
            VERSION=${{ github.sha }}
      - name: Push Frontend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: timnekk/sausage-frontend:latest
      - name: Push Backend-report to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend-report/
          push: true
          tags: timnekk/sausage-backend-report:latest

  add_helm_chart_to_nexus:
    name: Add Helm Chart To Nexus
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub

    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Install Helm Push
        run: helm plugin install https://github.com/chartmuseum/helm-push
      - name: Build Helm Dependencies
        run: helm dependency build ./sausage-store-chart
      - name: Package Helm chart
        run: helm package ./sausage-store-chart --version 0.1.0
      - name: Add Nexus Helm Repository
        run: |
          helm repo add nexus ${{ env.NEXUS_HELM_REPO }} \
            --username ${{ env.NEXUS_HELM_REPO_USER }} \
            --password ${{ env.NEXUS_HELM_REPO_PASSWORD }}
          helm repo update
      - name: Push Chart
        run: |
          curl -u ${{ env.NEXUS_HELM_REPO_USER }}:${{ env.NEXUS_HELM_REPO_PASSWORD }} --upload-file sausage-store-0.1.0.tgz ${{ env.NEXUS_HELM_REPO }}

  # Деплоим приложения в кластер Kubernetes с помощью helm-чарт
  deploy_helm_chart_to_kubernetes:
    name: Deploy Helm Chart To Kubernetes
    runs-on: ubuntu-latest
    needs: add_helm_chart_to_nexus

    steps:
    #### Опишите необходимые шаги
